#!/bin/bash
#### install wine
apt-get --fix-broken install -y
apt-get install -f -y # eksik bağımlılıkları tamamlaması için.
apt-get autoremove -y
apt-get update -y
apt-get upgrade -y
apt-get install printer-driver-all -y

apt-get autoremove -y
apt-get autoclean -y
apt-get update -y
